server: 
  port: 9000

#spring:
#  datasource:
#      driver-class-name: org.h2.Driver
#      url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
#      username: sa
#      password:
  kafka:
      consumer:
        bootstrap-servers: localhost:9092
        group-id: group_id
        auto-offset-reset: earliest
#        key-deserializer: com.example.kafka.DevicePacketDeserializer
#        value-deserializer: com.example.kafka.DevicePacketDeserializer
      producer:
        bootstrap-servers: localhost:9092
#        key-serializer: com.example.kafka.DevicePacketSerializer
#        value-serializer: com.example.kafka.DevicePacketSerializer

 # security:
 #     user: 
#         name : admin
 #        password: admin
#